version: '2'

services:
  php:
    build: php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php/www:/var/www/html
    links:
      - db
  
  db:
    image: mysql:5.7
    volumes:
     - /var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=shipping_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - '8080:80'
    depends_on:
     - db
